version: "1"

services:
  # Managed Redis Instance
  - type: redis
    name: lingogen-redis-bp
    region: ohio
    plan: free
    ipAllowList: [] # empty means only internal access

  # The FastAPI Backend
  - type: web
    name: lingogen-backend
    env: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    region: ohio
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lingogen-db-bp
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: lingogen-redis-bp
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: "https://lingo-gen-rho.vercel.app"
      - key: DEBUG
        value: "False"
      - key: GOOGLE_CLIENT_ID
        value: "500724399689-1jkl9pmjv2qu775108qev1n279d5mjga.apps.googleusercontent.com"

databases:
  # Managed PostgreSQL Database
  - name: lingogen-db-bp
    region: ohio
    plan: free
